### ISSUE TITLE
GraphAPI meeting information output is truncated

### ISSUE THREAD

**Issue by MikePHayward** [NunoFilipeMota/PublicScripts#1]
HI, 

first of all, thanks for the work on this - it's very much appreciated.

I'm trying to output the details of each meeting to a CSV, uncommenting the required code and basically copying the $roomsObj method to declare and then run it.

> 
    $roomsObj = [PSCustomObject] @{
        RoomName                = $room.nickname
        RoomSMTP                = $room.emailAddress
        From                    = Get-Date $From
        To                      = Get-Date $To
        totalMeetings           = "{0:N0}" -f $totalMeetings
        totalDuration           = "{0:N0}" -f $totalDuration
        totalAttendees          = "{0:N0}" -f $totalAttendees
        totalUniqueOrganizers   = If ($topOrganizers) {($topOrganizers.GetEnumerator() | Select Name | Measure).Count} Else {""}
        totalUniqueAttendees    = If ($topAttendees) {($topAttendees.GetEnumerator() | Select Name | Measure).Count} Else {""}
        totalReqAttendees       = $totalReqAttendees
        totalOptAttendees       = $totalOptAttendees
        Top5Organizers          = If ($topOrganizers) {($topOrganizers.GetEnumerator() | Sort -Property Value -Descending | Select -First 5 | % {"$($_.Key) ($($_.Value))"}) -Join ", "} Else {""}
        Top5Attendees           = If ($topAttendees) {($topAttendees.GetEnumerator() | Sort -Property Value -Descending | Select -First 5 | % {"$($_.Key) ($($_.Value))"}) -Join ", "} Else {""}
        totalAllDay             = "{0:N0}" -f $totalAllDay
        totalAM                 = "{0:N0}" -f $totalAM
        totalPM                 = "{0:N0}" -f $totalPM
        totalRecurring          = "{0:N0}" -f $totalRecurring
        totalSingle             = "{0:N0}" -f $totalSingle
    }
    $meetingsObj = [PSCustomObject] @{
           Start       = (Get-Date $meeting.start.dateTime).ToString() + " " + $meeting.start.timeZone
           End         = (Get-Date $meeting.end.dateTime).ToString() + " " + $meeting.end.timeZone
           Subject     = $meeting.subject
           importance  = $meeting.importance
           isAllDay    = $meeting.isAllDay
           MeetingRoom = $meeting.locations.locationUri -Join "; "
           attendees   = ($meeting.attendees.emailAddress | % {$_.address}) -Join "; "
           organizer   = $meeting.organizer.emailAddress.address
           type        = $meeting.type
           hasAttachments  = $meeting.hasAttachments
         }

    $roomsObj
    $roomsObj | Export-CSV "GetMeetingRoomStats_$(Get-Date -f 'yyyyMMdd').csv" -NoType -Append
    $meetingsObj
    $meetingsObj | Export-CSV "GetMeetingRoombookings_$(Get-Date -f 'yyyyMMdd').csv" -NoType -Append
    $count++

However , it appears doing this only returns the last meeting returned for each room, rather than a list of each room.

I've tried adding Counters or including the meeting ID to no avail - could you advise where I'm obviously going wrong?

Many thanks,
Mike

**Comment by NunoFilipeMota** [comment]
Hi Mike,

You are most welcome!   :)

If you want the details for each meeting, and from the title I assume you are using the Graph API version of the script, all you have to do is un-comment the following section:

        # # If you want to capture the details of each meeting
        # [PSCustomObject] @{
        #   Start       = (Get-Date $meeting.start.dateTime).ToString() + " " + $meeting.start.timeZone
        #   End         = (Get-Date $meeting.end.dateTime).ToString() + " " + $meeting.end.timeZone
        #   Subject     = $meeting.subject
        #   importance  = $meeting.importance
        #   isAllDay    = $meeting.isAllDay
        #   MeetingRoom = $meeting.locations.locationUri -Join "; "
        #   attendees   = ($meeting.attendees.emailAddress | % {$_.address}) -Join "; "
        #   organizer   = $meeting.organizer.emailAddress.address
        #   type        = $meeting.type
        #   hasAttachments  = $meeting.hasAttachments
        # }

Then, you can either export the object directly to a CSV file for example, or save it into an array and then export it at the end (I'd would do the former).

In your case, it seems you have the "$meetingsObj = [PSCustomObject] @{" part in the wrong section (i.e., outside of the second ForEach loop), so you are assigning only the details of the last meeting to that object. If you want to add the details to an array, you have to do something like "$meetingsObj += [PSCustomObject] @{", but it needs to be in the correct place.

But please just un-comment the section I mentioned above as you don't need additional code (unless you need extra information)   :)

Regards,
Nuno

**Comment by MikePHayward** [comment]
Thanks Nuno,

that's pointed me in the right direction.

I actually ended up moving this to an Azure Automation runbook. So storing it in an array allows me to send it as an email via the GraphAPI (who knew that was a thing...)

Thanks Again!
Mike

**Comment by NunoFilipeMota** [comment]
Nice!   :)
