### ISSUE TITLE
handling for on-premises mailboxes has changed or is incorrect

### ISSUE THREAD

**Issue by vyguy** [NunoFilipeMota/PublicScripts#2]
I am working in a hybrid environment. 
Running the script against a mailbox that has yet to be migrated produces this error:
'Unable to query Graph API: 'The remote server returned an error: (404) Not Found.'

As you can see, I don't receive the "REST API is not yet supported" error that you were expecting in lines 216/255. 
I'm not sure if this is a change in the service, or if it's because my on-premises roommailbox also has its user account enabled. 
In either case, you'd best be served by adding an OR statement to lines 216/255 to handle the additional 404 error response.

**Comment by vyguy** [comment]
Function Query-GraphAPI  hangs if the mailbox's email address has a hash. 
Example: #usidahoboiseFrontConfRoom@contoso.com

This causes the entire script to hang.

**Comment by NunoFilipeMota** [comment]
Thank you for the comment vyguy. As you probably know, the script doesn't work with on-prem mailboxes. I will update the code!
